### ISSUE TITLE
Homework #3

### ISSUE THREAD

**Issue by scurest** [rgibler/Intro2Cpp#2]
I was bored so unfortunately for you I decided to criticize your homework again. In [hw#3.cpp](https://github.com/rgibler/Intro2Cpp/blob/c62122e3bbfbd522c6a81c7253e524e63caf65d6/COSC1437/hw%233.cpp):

* `dayType::dayName` is never used. Just delete it.
* `RequestDay` is declared but never defined or used. Delete it.
* Typo in `"This this program` (I also didn't notice this for several hours...)
* In

        int previousDay = (dayNum - 1) % 7;

    Since `dayNum` is already in [0, 7), the `% 7` here does nothing.
* For `SetDayName(string usrInput)`, you take the parameter by value but you don't need to. It's better to take it by const reference (`const string& usrInput`) so that it won't be copied needlessly.
* `PrintDay`, `GetDay`, `GetNextDay`, `GetPrevDay` and `CalcDay` should all be const because they don't modify the `this` object, ie. declare them

            void PrintDay(int) const;
            int GetDay() const;
            int GetNextDay() const;
            int GetPreviousDay() const;
            int CalcDay() const;
* That `newDay = -25` thing has to go. Actually the problem is `printDay` has smooshed a whole bunch of functionality into one function

    * It handles both operating on an argument and operating on the current object's `dayNum` field. For example, if you have `day.PrintDay(x)` the `day` object _isn't even used_.
     * It decides where to print the day name (what if I didn't want it printed to cout? What if I didn't want a newline? etc)
    * It handles outputting errors

    Here's a better way

    ````
    const char* ToName() const {
        constexpr const char* names[] =
            { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" };
        return names[dayNum];
    }
    ````

    * It handles only the current object. If you want to go from a day number to a name, put the number into a `dayType` object first (and errors can be handled there).
    * It lets the caller decide what to do with the name (print it, convert to string, etc.)
    * Since you know `dayNum` is in [0,7), you don't have to handle any errors.

    The switch in `SetDayName` can be refactored to use an array too.

* Related, but the `GetNextDay`, `GetPrevDay`, etc. members should return `dayType` objects instead of integers.
* `CalcDay` is tightly coupled to the main function. It does a whole lot more than calculating a day, including error reporting and printing, which should all be left to the caller for better flexibility.
* Don't just give up on negative values lol. If you do `x % 7` and x is negative, you get a (possibly) negative remainder. If this happens, you just need to add 7 to get the corresponding positive one.
* You should print errors to `cerr`, not `cout`.
* You have trailing whitespace (your editor can probably be configured to remove this automatically).

-----

I wrote [a version](https://gist.github.com/scurest/80c203cbececd7e2ee48efcb849f1ce3) that incorporates these changes and cleanly separates the logic of manipulating the week day from the main program that interacts with the user. Maybe it will be moderately helpful :)

Feel free to close this btw ;;;

**Comment by rgibler** [comment]
Thanks a lot man! Sorry I just saw this. I'll go back and make the changes haha
